name: Build UI Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build