name: Compile and Test Contract Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  compile-and-test:
    name: Compile and Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Compile
        run: npm run compile
      
      - name: Run Test
        run: npm run test