name: Compile and Test Contract

on:
  pull_request:
    branches:
      - main

jobs:
  compile-and-test:
    name: Compile and Test Job
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contract
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Cache dependencies
        id: cache-node-dep
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-dependencies-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-dep.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Compile
        run: npm run compile
      
      - name: Run Test
        run: npm run test